-- Preferências persistentes do painel administrativo.
create table if not exists public.configuracao_sistema (
  id_configuracao bigint generated by default as identity primary key,
  id_usuario uuid not null references auth.users(id) on delete cascade,
  nome_studio text not null default 'Studio de Dança Keli Dalpian',
  telefone text,
  email text,
  endereco text,
  notificacoes_automaticas boolean not null default true,
  lembretes_mensalidade boolean not null default true,
  avisos_aula boolean not null default true,
  idioma text not null default 'Português (BR)',
  fuso_horario text not null default 'Brasília (BR)',
  enviar_avisos_administrativos boolean not null default true,
  enviar_confirmacao_matriculas boolean not null default true,
  atualizado_em timestamptz not null default now(),
  constraint configuracao_sistema_usuario_unique unique (id_usuario)
);

create or replace function public.admin_obter_configuracoes()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  configuracao public.configuracao_sistema%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Acesso administrativo não autorizado.' using errcode = '42501';
  end if;

  insert into public.configuracao_sistema (id_usuario)
  values (auth.uid())
  on conflict (id_usuario) do nothing;

  select * into configuracao
  from public.configuracao_sistema
  where id_usuario = auth.uid();

  return to_jsonb(configuracao);
end;
$$;

create or replace function public.admin_salvar_configuracoes(
  p_nome_studio text,
  p_telefone text,
  p_email text,
  p_endereco text,
  p_notificacoes_automaticas boolean,
  p_lembretes_mensalidade boolean,
  p_avisos_aula boolean,
  p_idioma text,
  p_fuso_horario text,
  p_enviar_avisos_administrativos boolean,
  p_enviar_confirmacao_matriculas boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  configuracao public.configuracao_sistema%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Acesso administrativo não autorizado.' using errcode = '42501';
  end if;

  insert into public.configuracao_sistema (
    id_usuario, nome_studio, telefone, email, endereco,
    notificacoes_automaticas, lembretes_mensalidade, avisos_aula,
    idioma, fuso_horario, enviar_avisos_administrativos,
    enviar_confirmacao_matriculas, atualizado_em
  ) values (
    auth.uid(),
    coalesce(nullif(trim(p_nome_studio), ''), 'Studio de Dança Keli Dalpian'),
    nullif(trim(p_telefone), ''),
    nullif(trim(p_email), ''),
    nullif(trim(p_endereco), ''),
    coalesce(p_notificacoes_automaticas, true),
    coalesce(p_lembretes_mensalidade, true),
    coalesce(p_avisos_aula, true),
    coalesce(nullif(trim(p_idioma), ''), 'Português (BR)'),
    coalesce(nullif(trim(p_fuso_horario), ''), 'Brasília (BR)'),
    coalesce(p_enviar_avisos_administrativos, true),
    coalesce(p_enviar_confirmacao_matriculas, true),
    now()
  )
  on conflict (id_usuario) do update set
    nome_studio = excluded.nome_studio,
    telefone = excluded.telefone,
    email = excluded.email,
    endereco = excluded.endereco,
    notificacoes_automaticas = excluded.notificacoes_automaticas,
    lembretes_mensalidade = excluded.lembretes_mensalidade,
    avisos_aula = excluded.avisos_aula,
    idioma = excluded.idioma,
    fuso_horario = excluded.fuso_horario,
    enviar_avisos_administrativos = excluded.enviar_avisos_administrativos,
    enviar_confirmacao_matriculas = excluded.enviar_confirmacao_matriculas,
    atualizado_em = now()
  returning * into configuracao;

  return to_jsonb(configuracao);
end;
$$;

revoke all on table public.configuracao_sistema from public;
revoke all on function public.admin_obter_configuracoes() from public;
revoke all on function public.admin_salvar_configuracoes(text, text, text, text, boolean, boolean, boolean, text, text, boolean, boolean) from public;
grant execute on function public.admin_obter_configuracoes() to authenticated;
grant execute on function public.admin_salvar_configuracoes(text, text, text, text, boolean, boolean, boolean, text, text, boolean, boolean) to authenticated;
