-- Carrinho do aluno para persistir os itens escolhidos no modal da loja.
create table if not exists public.carrinho_aluno (
  id_carrinho bigint generated by default as identity primary key,
  id_usuario uuid not null references auth.users(id) on delete cascade,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (id_usuario)
);

create table if not exists public.item_carrinho_aluno (
  id_item bigint generated by default as identity primary key,
  id_carrinho bigint not null references public.carrinho_aluno(id_carrinho) on delete cascade,
  id_produto integer not null references public.produto(id_produto) on delete cascade,
  tamanho text not null default 'Único',
  quantidade integer not null check (quantidade > 0),
  preco_unitario numeric(10, 2) not null check (preco_unitario >= 0),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (id_carrinho, id_produto, tamanho)
);

alter table public.carrinho_aluno enable row level security;
alter table public.item_carrinho_aluno enable row level security;

drop policy if exists "aluno gerencia seu carrinho" on public.carrinho_aluno;
create policy "aluno gerencia seu carrinho"
  on public.carrinho_aluno for all to authenticated
  using (id_usuario = auth.uid())
  with check (id_usuario = auth.uid());

drop policy if exists "aluno gerencia itens do seu carrinho" on public.item_carrinho_aluno;
create policy "aluno gerencia itens do seu carrinho"
  on public.item_carrinho_aluno for all to authenticated
  using (exists (select 1 from public.carrinho_aluno c where c.id_carrinho = item_carrinho_aluno.id_carrinho and c.id_usuario = auth.uid()))
  with check (exists (select 1 from public.carrinho_aluno c where c.id_carrinho = item_carrinho_aluno.id_carrinho and c.id_usuario = auth.uid()));
