-- Registra pedidos do aluno e finaliza o carrinho em uma única operação.
create table if not exists public.pedidos (
  id_pedido bigint generated by default as identity primary key,
  id_usuario uuid not null references auth.users(id) on delete cascade,
  forma_pagamento text not null check (forma_pagamento in ('pix', 'card')),
  status text not null default 'pendente',
  subtotal numeric(10, 2) not null check (subtotal >= 0),
  retirada numeric(10, 2) not null default 0 check (retirada >= 0),
  total numeric(10, 2) not null check (total >= 0),
  criado_em timestamptz not null default now()
);

create table if not exists public.itens_pedido (
  id_item_pedido bigint generated by default as identity primary key,
  id_pedido bigint not null references public.pedidos(id_pedido) on delete cascade,
  id_produto integer not null references public.produto(id_produto),
  tamanho text not null,
  quantidade integer not null check (quantidade > 0),
  preco_unitario numeric(10, 2) not null check (preco_unitario >= 0)
);

alter table public.pedidos enable row level security;
alter table public.itens_pedido enable row level security;

drop policy if exists "aluno consulta seus pedidos" on public.pedidos;
create policy "aluno consulta seus pedidos" on public.pedidos for select to authenticated using (id_usuario = auth.uid());
drop policy if exists "aluno consulta itens de seus pedidos" on public.itens_pedido;
create policy "aluno consulta itens de seus pedidos" on public.itens_pedido for select to authenticated using (exists (select 1 from public.pedidos p where p.id_pedido = itens_pedido.id_pedido and p.id_usuario = auth.uid()));

create or replace function public.finalizar_pedido_aluno(p_forma_pagamento text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  usuario uuid := auth.uid();
  carrinho bigint;
  novo_pedido bigint;
  total numeric(10, 2);
begin
  select c.id_carrinho into carrinho from public.carrinho_aluno c where c.id_usuario = usuario for update;
  if carrinho is null then raise exception 'Carrinho não encontrado.'; end if;

  select coalesce(sum(i.quantidade * i.preco_unitario), 0) into total
  from public.item_carrinho_aluno i where i.id_carrinho = carrinho;
  if total <= 0 then raise exception 'O carrinho está vazio.'; end if;
  if p_forma_pagamento not in ('pix', 'card') then raise exception 'Forma de pagamento inválida.'; end if;

  insert into public.pedidos (id_usuario, forma_pagamento, subtotal, total)
  values (usuario, p_forma_pagamento, total, total)
  returning id_pedido into novo_pedido;

  insert into public.itens_pedido (id_pedido, id_produto, tamanho, quantidade, preco_unitario)
  select novo_pedido, i.id_produto, i.tamanho, i.quantidade, i.preco_unitario
  from public.item_carrinho_aluno i where i.id_carrinho = carrinho;

  delete from public.item_carrinho_aluno where id_carrinho = carrinho;
  return jsonb_build_object('id_pedido', novo_pedido, 'total', total, 'status', 'pendente');
end;
$$;

grant execute on function public.finalizar_pedido_aluno(text) to authenticated;
